// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: snapshot.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SnapshotTransfer_GetLogStatus_FullMethodName      = "/snapshot.SnapshotTransfer/GetLogStatus"
	SnapshotTransfer_StreamLogRange_FullMethodName    = "/snapshot.SnapshotTransfer/StreamLogRange"
	SnapshotTransfer_ConfirmCompaction_FullMethodName = "/snapshot.SnapshotTransfer/ConfirmCompaction"
)

// SnapshotTransferClient is the client API for SnapshotTransfer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SnapshotTransfer is called by the Snapshot & Backup service against the
// current leader (GetLogStatus/ConfirmCompaction) or any node
// (StreamLogRange, since entries served there are already committed).
// See spec §9.4.
type SnapshotTransferClient interface {
	GetLogStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*LogStatusReply, error)
	StreamLogRange(ctx context.Context, in *LogRangeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error)
	ConfirmCompaction(ctx context.Context, in *CompactionAck, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type snapshotTransferClient struct {
	cc grpc.ClientConnInterface
}

func NewSnapshotTransferClient(cc grpc.ClientConnInterface) SnapshotTransferClient {
	return &snapshotTransferClient{cc}
}

func (c *snapshotTransferClient) GetLogStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*LogStatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogStatusReply)
	err := c.cc.Invoke(ctx, SnapshotTransfer_GetLogStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotTransferClient) StreamLogRange(ctx context.Context, in *LogRangeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SnapshotTransfer_ServiceDesc.Streams[0], SnapshotTransfer_StreamLogRange_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogRangeRequest, LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SnapshotTransfer_StreamLogRangeClient = grpc.ServerStreamingClient[LogEntry]

func (c *snapshotTransferClient) ConfirmCompaction(ctx context.Context, in *CompactionAck, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SnapshotTransfer_ConfirmCompaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnapshotTransferServer is the server API for SnapshotTransfer service.
// All implementations must embed UnimplementedSnapshotTransferServer
// for forward compatibility.
//
// SnapshotTransfer is called by the Snapshot & Backup service against the
// current leader (GetLogStatus/ConfirmCompaction) or any node
// (StreamLogRange, since entries served there are already committed).
// See spec §9.4.
type SnapshotTransferServer interface {
	GetLogStatus(context.Context, *emptypb.Empty) (*LogStatusReply, error)
	StreamLogRange(*LogRangeRequest, grpc.ServerStreamingServer[LogEntry]) error
	ConfirmCompaction(context.Context, *CompactionAck) (*emptypb.Empty, error)
	mustEmbedUnimplementedSnapshotTransferServer()
}

// UnimplementedSnapshotTransferServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSnapshotTransferServer struct{}

func (UnimplementedSnapshotTransferServer) GetLogStatus(context.Context, *emptypb.Empty) (*LogStatusReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLogStatus not implemented")
}
func (UnimplementedSnapshotTransferServer) StreamLogRange(*LogRangeRequest, grpc.ServerStreamingServer[LogEntry]) error {
	return status.Error(codes.Unimplemented, "method StreamLogRange not implemented")
}
func (UnimplementedSnapshotTransferServer) ConfirmCompaction(context.Context, *CompactionAck) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmCompaction not implemented")
}
func (UnimplementedSnapshotTransferServer) mustEmbedUnimplementedSnapshotTransferServer() {}
func (UnimplementedSnapshotTransferServer) testEmbeddedByValue()                          {}

// UnsafeSnapshotTransferServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnapshotTransferServer will
// result in compilation errors.
type UnsafeSnapshotTransferServer interface {
	mustEmbedUnimplementedSnapshotTransferServer()
}

func RegisterSnapshotTransferServer(s grpc.ServiceRegistrar, srv SnapshotTransferServer) {
	// If the following call panics, it indicates UnimplementedSnapshotTransferServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SnapshotTransfer_ServiceDesc, srv)
}

func _SnapshotTransfer_GetLogStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotTransferServer).GetLogStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotTransfer_GetLogStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotTransferServer).GetLogStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotTransfer_StreamLogRange_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogRangeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SnapshotTransferServer).StreamLogRange(m, &grpc.GenericServerStream[LogRangeRequest, LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SnapshotTransfer_StreamLogRangeServer = grpc.ServerStreamingServer[LogEntry]

func _SnapshotTransfer_ConfirmCompaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompactionAck)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotTransferServer).ConfirmCompaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotTransfer_ConfirmCompaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotTransferServer).ConfirmCompaction(ctx, req.(*CompactionAck))
	}
	return interceptor(ctx, in, info, handler)
}

// SnapshotTransfer_ServiceDesc is the grpc.ServiceDesc for SnapshotTransfer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SnapshotTransfer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "snapshot.SnapshotTransfer",
	HandlerType: (*SnapshotTransferServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLogStatus",
			Handler:    _SnapshotTransfer_GetLogStatus_Handler,
		},
		{
			MethodName: "ConfirmCompaction",
			Handler:    _SnapshotTransfer_ConfirmCompaction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogRange",
			Handler:       _SnapshotTransfer_StreamLogRange_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "snapshot.proto",
}

const (
	SnapshotCatalog_GetLatestSnapshotInfo_FullMethodName = "/snapshot.SnapshotCatalog/GetLatestSnapshotInfo"
	SnapshotCatalog_FetchSnapshot_FullMethodName         = "/snapshot.SnapshotCatalog/FetchSnapshot"
)

// SnapshotCatalogClient is the client API for SnapshotCatalog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SnapshotCatalog is queried by any consensus node (leader, follower, or a
// brand-new node) to independently discover and fetch the latest stable
// snapshot, per the periodic catch-up rule in §5.3.
type SnapshotCatalogClient interface {
	GetLatestSnapshotInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SnapshotInfo, error)
	FetchSnapshot(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapshotChunk], error)
}

type snapshotCatalogClient struct {
	cc grpc.ClientConnInterface
}

func NewSnapshotCatalogClient(cc grpc.ClientConnInterface) SnapshotCatalogClient {
	return &snapshotCatalogClient{cc}
}

func (c *snapshotCatalogClient) GetLatestSnapshotInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SnapshotInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotInfo)
	err := c.cc.Invoke(ctx, SnapshotCatalog_GetLatestSnapshotInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotCatalogClient) FetchSnapshot(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapshotChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SnapshotCatalog_ServiceDesc.Streams[0], SnapshotCatalog_FetchSnapshot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, SnapshotChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SnapshotCatalog_FetchSnapshotClient = grpc.ServerStreamingClient[SnapshotChunk]

// SnapshotCatalogServer is the server API for SnapshotCatalog service.
// All implementations must embed UnimplementedSnapshotCatalogServer
// for forward compatibility.
//
// SnapshotCatalog is queried by any consensus node (leader, follower, or a
// brand-new node) to independently discover and fetch the latest stable
// snapshot, per the periodic catch-up rule in §5.3.
type SnapshotCatalogServer interface {
	GetLatestSnapshotInfo(context.Context, *emptypb.Empty) (*SnapshotInfo, error)
	FetchSnapshot(*emptypb.Empty, grpc.ServerStreamingServer[SnapshotChunk]) error
	mustEmbedUnimplementedSnapshotCatalogServer()
}

// UnimplementedSnapshotCatalogServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSnapshotCatalogServer struct{}

func (UnimplementedSnapshotCatalogServer) GetLatestSnapshotInfo(context.Context, *emptypb.Empty) (*SnapshotInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestSnapshotInfo not implemented")
}
func (UnimplementedSnapshotCatalogServer) FetchSnapshot(*emptypb.Empty, grpc.ServerStreamingServer[SnapshotChunk]) error {
	return status.Error(codes.Unimplemented, "method FetchSnapshot not implemented")
}
func (UnimplementedSnapshotCatalogServer) mustEmbedUnimplementedSnapshotCatalogServer() {}
func (UnimplementedSnapshotCatalogServer) testEmbeddedByValue()                         {}

// UnsafeSnapshotCatalogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnapshotCatalogServer will
// result in compilation errors.
type UnsafeSnapshotCatalogServer interface {
	mustEmbedUnimplementedSnapshotCatalogServer()
}

func RegisterSnapshotCatalogServer(s grpc.ServiceRegistrar, srv SnapshotCatalogServer) {
	// If the following call panics, it indicates UnimplementedSnapshotCatalogServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SnapshotCatalog_ServiceDesc, srv)
}

func _SnapshotCatalog_GetLatestSnapshotInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotCatalogServer).GetLatestSnapshotInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotCatalog_GetLatestSnapshotInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotCatalogServer).GetLatestSnapshotInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotCatalog_FetchSnapshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SnapshotCatalogServer).FetchSnapshot(m, &grpc.GenericServerStream[emptypb.Empty, SnapshotChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SnapshotCatalog_FetchSnapshotServer = grpc.ServerStreamingServer[SnapshotChunk]

// SnapshotCatalog_ServiceDesc is the grpc.ServiceDesc for SnapshotCatalog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SnapshotCatalog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "snapshot.SnapshotCatalog",
	HandlerType: (*SnapshotCatalogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLatestSnapshotInfo",
			Handler:    _SnapshotCatalog_GetLatestSnapshotInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FetchSnapshot",
			Handler:       _SnapshotCatalog_FetchSnapshot_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "snapshot.proto",
}
